# Form implementation generated from reading ui file '.\ui\design.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(256, 206)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.monitors_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.monitors_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.monitors_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.monitors_frame.setObjectName("monitors_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.monitors_frame)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.addWidget(self.monitors_frame, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.gridFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_3.setSpacing(12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.startup_checkbox = QtWidgets.QCheckBox(parent=self.gridFrame)
        self.startup_checkbox.setMinimumSize(QtCore.QSize(0, 25))
        self.startup_checkbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.startup_checkbox.setText("")
        self.startup_checkbox.setAutoRepeat(False)
        self.startup_checkbox.setObjectName("startup_checkbox")
        self.gridLayout_3.addWidget(self.startup_checkbox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridFrame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.rescan_button = QtWidgets.QPushButton(parent=self.gridFrame)
        self.rescan_button.setMinimumSize(QtCore.QSize(0, 25))
        self.rescan_button.setObjectName("rescan_button")
        self.gridLayout_3.addWidget(self.rescan_button, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.gridFrame, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "General settings"))
        self.label.setText(_translate("MainWindow", "Send ON/OFF signal to:"))
        self.label_2.setText(_translate("MainWindow", "Run at startup"))
        self.rescan_button.setText(_translate("MainWindow", "Rescan monitors"))
