# Form implementation generated from reading ui file '.\src\ui\design.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(256, 98)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.startup_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.startup_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        self.startup_checkbox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.startup_checkbox.setAutoRepeat(False)
        self.startup_checkbox.setObjectName("startup_checkbox")
        self.gridLayout.addWidget(self.startup_checkbox, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.gridFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.gridFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.addWidget(self.gridFrame, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startup_checkbox.setText(_translate("MainWindow", "Run at startup"))
        self.label.setText(_translate("MainWindow", "Send ON/OFF signal to:"))
