name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          add-tools-to-path: true
          cache: true

      - name: Configure and build with CMake
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release

      - name: Deploy Qt
        shell: pwsh
        run: |
          cd build
          $windeployqtPath = "D:\a\QMS\Qt\6.8.0\msvc2022_64\bin\windeployqt6.exe"
          $qmlDir = "D:\a\QMS\QMS\Resources\qml"
          if (Test-Path $windeployqtPath) {
              & $windeployqtPath `
                  --exclude-plugins qsvgicon,qsvg,qico,qjpeg,qgif,qnetworklistmanager,qtuiotouchplugin `
                  --no-opengl-sw `
                  --no-system-dxc-compiler `
                  --no-compiler-runtime `
                  --no-translations `
                  --no-system-d3d-compiler `
                  --qmldir $qmlDir `
                  D:\a\QMS\QMS\build\release\QMS.exe
          } else {
              Write-Error "windeployqt not found at the expected path!"
              exit 1
          }

      - name: Rename release folder
        shell: pwsh
        run: |
          $releaseDir = "build/release"
          $newDir = "QMS"
          if (Test-Path $releaseDir) {
              Rename-Item -Path $releaseDir -NewName $newDir
          } else {
              Write-Error "Release folder not found!"
              exit 1
          }

      - name: Zip binaries folder
        shell: pwsh
        run: |
          $zipFile = "build/QMS_msvc_64.zip"
          $folder = "build/QMS"
          Compress-Archive -Path $folder -DestinationPath $zipFile

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QMS_msvc_64
          path: build/QMS_msvc_64.zip